name: Vouch Check PR

on:
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  contents: read
  pull-requests: write

jobs:
  check-pr-author:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Author Vouch Status
        uses: mitchellh/vouch/action/check-pr@d30c6a4e7a599cb3409251dcdd97a5724d7840f6
        with:
          pr-number: ${{ github.event.pull_request.number }}
          repo: ${{ github.repository }}
          auto-close: true
          require-vouch: true
          vouched-file: .github/VOUCHED.td
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
